### ISSUE TITLE
Set up CI for matlab testing 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#133]
See here: https://nl.mathworks.com/solutions/continuous-integration.html?s_tid=srchtitle

Preferably with github action if possible. :wink:

**Comment by tanguyduval** [comment]
@Remi-Gau if you need help on testing Matlab repo on Github, @agahkarakuzu went through this for the repo https://github.com/qMRLab/qMRLab
He might be able to answer few of your questions

You might be interested in this issue:
https://github.com/qMRLab/qMRLab/issues/412

Hope that helps :)

**Comment by tanguyduval** [comment]
Agah also made a very nice blog post about this:
https://qmrlab.org/2020/06/16/matlab-ci.html

Best

**Comment by Remi-Gau** [comment]
ha thanks I knew about the blog post but I remember that it described matlab CI that could only be run on some "self-hosted" azure  thingy magic.

Apparently there is some new stuff. Thanks for the pointer and pinging me. :-)

**Comment by agahkarakuzu** [comment]
Hey @Remi-Gau Matlab actually opened a license for public projects on Azure. Unless there is need for transformation tools (app compiler and code translator), it works like charm. 

I set one up at https://github.com/qmrlab/qmrlab

.azure-pipelines.yml at the root points to that service.

**Comment by Remi-Gau** [comment]
Awesome thanks @agahkarakuzu 

Will have a look (when I got the time :-) )
