### ISSUE TITLE
Bug in `query.m`: Sub-function `get_modalities` counts `scans` and `sess` as modality

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#164]
In function `get_modalities` (l:138), modalities are detected by searchin non-empty structure:
```
    hasmod = arrayfun(@(y) structfun(@(x) isstruct(x) & ~isempty(x), y), ...
                      BIDS.subjects, 'UniformOutput', false);
    hasmod = any([hasmod{:}], 2);
    modalities   = fieldnames(BIDS.subjects)';
    modalities   = modalities(hasmod);
```
However, the fields for `scans` and `sess` are also structures, and so will be considered as modality.
Actually they are not filled, but once they will it may cause problems.

**Comment by Remi-Gau** [comment]
yeah I had opened #145 as a reminder to get that ball rolling but you are correct that this will cause problems when asking for modalities
