### ISSUE TITLE
Feature request: usage of regexp in query for subjects

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#186]
Some datasets can contains large amount of subjects, and querry with a list of subjects may be not convinient.
It would be nice if for 'sub' query, user can enter a regexp to select a subset of subjects.

Ex.:

```
% retrive only control subjects
control = bids.query(BIDS, 'subjects', 'sub', 'HC.*');

% 
patients = bids.query(BIDS, 'subjects', 'sub', 'AD.*');
```

The only place needed to be changed is in [query.m](https://github.com/bids-standard/bids-matlab/blob/c9870405409ed42027ccae4744e5ad80995d8c8f/%2Bbids/query.m#L130).
Instead of returning just passed subject list, return list of matched subjects.

**Comment by Remi-Gau** [comment]
Yup I was thinking the same for some things in our lab: the subject label can be used to specify "group" belonging:-
- sub-control01
- sub-patient01

Passing a regex would be VERY useful for only select those belonging to a group.

Though ideally group belonging should be encoded in the participants.tsv, it feel thing that can be supported easily by query.

Not sure it makes as much sense for session.

**Comment by nbeliy** [comment]
Sessions and entities will have a limited set of values. The need of regexp is not that important.
