### ISSUE TITLE
query does not cover 'acq' and 'rec'

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#2]
Playing around with a dataset that has different `acq` for the bold data and I realized that bids.query does not cover that parameter (nor `rec`).

It would be useful to have the possibility to just do:
fullbrain_bold_ls = bids.query(BIDS, 'data', 'sub', '01', 'type', 'bold', **'acq', 'fullbrain'**).

`acq` and `rec` are already listed in the structure returned by `layout` should it should be fairly straightforward. @gllmflndn you know those functions better so do you want to have a go or should I have a crack at it?

**Comment by gllmflndn** [comment]
Hi @Remi-Gau,

The code would deserve serious refactoring and documenting but this feature should already be available. It is implemented here:
https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/query.m#L77-L81

I just tried on the example dataset `7t_trt` and it seems to work for me:
````
>> bids.query(BIDS,'data','sub','01','ses','1','type','bold','acq','fullbrain')

ans =

  2x1 cell array

    {'/BIDS-examples/7t_trt/sub-01/ses-1/func/sub-01_ses-1_task-rest_acq-fullbrain_run-1_bold.nii.gz'}
    {'/BIDS-examples/7t_trt/sub-01/ses-1/func/sub-01_ses-1_task-rest_acq-fullbrain_run-2_bold.nii.gz'}
````

Do you get an empty output for the same query?

**Comment by Remi-Gau** [comment]
Hum... Not sure what I did yesterday evening but it threw an error that I am not able to reproduce now... I will close the issue and file it under PIBKAC.
