### ISSUE TITLE
Inefficient dependencies calculations

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#209]
The current way the dependencies are calculated are quite inefficient and may produce large lags on big datasets.

In my fork [nbeliy/bids-matlab/tree/beliy-dependencies](https://github.com/nbeliy/bids-matlab/tree/beliy-dependencies) I implemented a major optimization, which improve calculation by order of magnitude (seconds instead of minutes).
Unfortunately this fork diverged too much from the main dev, so I can't make quickly a new branch and merge request.

Idea is remember the index of latest group change (when the name up to suffix change) and basename change (name up to the extension).

If for a new file the basename is the same as in previous, all calculations will give the same result as in previous calculations, so we can just copy previous structure and adapt the filename and suffix. All such files will be in `data` dependencies, so we can go from to index where the basename changed for the last time and add current file to dependency, and for the current file, we can add only the previous one as dependency.

For the groups, is the same but without copy.

Modifications starts [there](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L182). 

**Obviously it relies that list of files is ordered alphabetically.**

- [L182:](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L182) initialisation of variables
```matlab
    index_group = 0;
    group_base = '';
    group_len = 1;
    index_data = 0;
    data_base = '';
    data_len = 1;
```

- [L192:](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L192) If basename does not change, just copiyng previous structure with change of filename, extension and dependency
```matlab
      if strncmp(data_base, file_list{i}, data_len)
        subject.(modality)(end+1, 1) = subject.(modality)(end, 1);
        subject.(modality)(end, 1).ext = file_list{i}(data_len:end);
        subject.(modality)(end, 1).filename = file_list{i};
        dep_fname = fullfile(pth, subject.(modality)(end-1, 1).filename);
        subject.(modality)(end).dependencies.data{end+1} = dep_fname;
```

- [L210:](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L210) looping over files with same basename and adding current file to dependency
```matlab
        for di = index_data:i-1
            subject.(modality)(di).dependencies.data{end+1} = fullpath_filename;
          end;
```

- [L215](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L215) basename changes, setting new values
```matlab
         index_data = i;
          data_len = find(file_list{i} == '.', 1);
          data_base = file_list{i}(1:data_len);
```

- [L219](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L219) Looping over files in the same group and adding the dependencies
```matlab
          for gi = index_group:i
            dep_fname = fullfile(pth, subject.(modality)(gi).filename);
            subject.(modality)(end).dependencies.group{end+1} = dep_fname;
            subject.(modality)(gi).dependencies.group{end+1} = fullpath_filename;
          end
```

- [L228](https://github.com/nbeliy/bids-matlab/blob/64fd39e42caeb5c10ed6b7e23e85a3e5f7fc6ad5/%2Bbids/layout.m#L228) Group changes, setting new values
```matlab
        index_group = i;
        group_len = find(file_list{i} == '_', 1, 'last');
        group_base = file_list{i}(1:group_len);
        
        index_data = i;
        data_len = find(file_list{i} == '.', 1);
        data_base = file_list{i}(1:data_len);
```

**Comment by Remi-Gau** [comment]
Sounds cool !
OK I will try to have a look later this week: need to implement some other things on our lab's pipeline with what we already have.

**Comment by nbeliy** [comment]
Hi Remi, is there any news about this issue?
It is the last part needed by CRC in order to switch to official bids-matlab from my private branch.

**Comment by Remi-Gau** [comment]
Hey,
Sorry for being so freaking slow on all of this.
So I went through a bit of a BIDS-Matlab marathon and started implementing this on a branch on my fork during the weekend.
I need to revisit it as it seemed to fail for some datasets: wanna make sure I did not mess things up.


Sent from my Galaxy

**Comment by Remi-Gau** [comment]
@nbeliy 

There are still some tests failing in #243 but I would not mind you having a look already to make sure that the PR captures the spirit of your suggestions.

So far I have not seem a huge speed up gain (7 seconds on running layout on all the bids-example) but I strongly suspect the gain might be more substantial on very big datasets (especially many files per subject) rather than many small datasets.

I will try to get my hand on a couple of large and  wide datasets to get some "benchmarks".
