### ISSUE TITLE
Not crashing nut not copying either, under Windows.

### ISSUE THREAD

**Issue by ChristophePhillips** [bids-standard/bids-matlab#241]
When copying files, there is a call to the system copy function `cp` but with Windows it doesn't work.
The code uses a `try... catch...` approach to then force the copying with built in Matlab/Octave function, assuming a Matlab/Octove error. Trouble is, at least on my Win10 with Matlab R2015b, there is no proper error, so the `catch` part is not ran no file gets copied

See code around:
https://github.com/bids-standard/bids-matlab/blob/24613789bb6b5e4dc1fe56d6e7572612842679b8/%2Bbids/copy_to_derivative.m#L309

**Comment by Remi-Gau** [comment]
hopefully #242 should fix that

I tested on my windows machine and the test passes and the data is being copied

do you think you could test from my `copy_windows` branch?

https://github.com/Remi-Gau/bids-matlab/tree/copy_windows

**Comment by ChristophePhillips** [comment]
Thanks, it seems like it's doing the job. 😀 

But I found a little bug elsewhere, around l.174 and following:
https://github.com/bids-standard/bids-matlab/blob/f9d2bd37d2183a5a1142d88824113c90d6d20a59/%2Bbids/copy_to_derivative.m#L174

````
    copy_with_symlink(src, target, p.Results.verbose);
    if exist(bids.internal.file_utils(src, 'ext', '.json'), 'file')
      copy_with_symlink(bids.internal.file_utils(src, 'ext', '.json'), ...
                        bids.internal.file_utils(target, 'ext', '.json'));
    end
````
where the 3rd argument (verbose flag) is not passed in the `copy_with_symlink` call. 
A simple fix is adding the `p.Results.verbose` as 3rd argument:
````
    copy_with_symlink(src, target, p.Results.verbose);
    if exist(bids.internal.file_utils(src, 'ext', '.json'), 'file')
      copy_with_symlink(bids.internal.file_utils(src, 'ext', '.json'), ...
                        bids.internal.file_utils(target, 'ext', '.json'), ...
                        p.Results.verbose);
    end
````

Other option is setting that argument to `false` if not specified when calling `copy_with_symlink`. 
Or doing both for extra safety?

**Comment by Remi-Gau** [comment]
Oh nice thanks!!

Just fixed that too.

> Other option is setting that argument to `false` if not specified when calling `copy_with_symlink`.
> Or doing both for extra safety?

I think I was more thinking of creating a dedicated function for all the print to screen stuff, have the default verbose flag define only there and channel all the message printing through that.

Otherwise you end up settings the same defaults in each function, subfunction...
