### ISSUE TITLE
Behavior question: do we want to index json as other files when runnning layout with use_schema=false

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#250]
> It was suggested by @arnodelorme in here

Then will it be possible to get json files only if they are not metadada for data?
A json file will be created for each file in derivative, then to do query I will need to add `'extention', '.nii'` each time. 

Also, if he want to get metadata json, they can be retrived with `query('metafiles')`

_Originally posted by @nbeliy in https://github.com/bids-standard/bids-matlab/issues/243#issuecomment-853858299_

**Comment by nbeliy** [comment]
Are there any decisions related to that?

**Comment by Remi-Gau** [comment]
I keep thinking about this  and I am more and more tempted to not index json even for schemaless datasets. I think we will go with behavior for the first release.
