### ISSUE TITLE
bids layout craches when processing bids-incompatible filenames

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#267]
When `bids.layout` encounters badly formatted bidsified names, the internal function `bids.internal.parce_filename` returns 
an empty structure, which usually crashes the following code (it tries to access `suffix`, `entities` fields). 

Crash is not followed by any meaningfull error/warning message, because `verbose` option in `parce_filenames` is never used.

Examples of problematic names:
```
func_task-AXcpt_bold.json
anat_T1w.json
task-AXcpt.json
```

**Comment by Remi-Gau** [comment]
your issue and PR are super timely: I had literally made a note last week to tackle those issues, I had encountered super recently too.
