### ISSUE TITLE
Standardising API

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#293]
function / classes to update

- [x] bids.init
- [x] bids.layout
- [ ] bids.Description (will be done later as the whole class should be updated)
- [x] bids.derivatives_json
- [x] bids.copy_to_derivative

---

Realising that overall bids-matlab is not super consistent in when something should be called as an argument or as "parameter: value" pair.

I think I would prefer to standardize this a bit before the first release.
```matlab
BIDS = bids.layout(root, ...
                               use_schema,  ...
                               index_derivatives,  ...
                               tolerant,  ...
                               verbose)

query = bids.query(BIDS, query, filter)

bids.copy_to_derivative(BIDS, pipeline_name,...
                            out_path, ...
                            filter, ...
                            'unzip', true, ...
                            'force', false, ...
                            'skip_dep', false, ...
                            'use_schema', use_schema, ...
                            'verbose', true);

file = bids.File2(filename, 'use_schema', false ...
                  'tolerant', true);

report = bids.report(BIDS, ...
                     'filter', filter, ...
                     'output_path', output_path, ...
                     'read_nifti', true, ...
                     'verbose', true);
```

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-matlab/pull/289#r749922089_

**Comment by Remi-Gau** [comment]
Should probably ALWAYS be `parameter: value` pairs.

Anything that is a boolean:
- `index_derivatives`
- `verbose`
- `tolerant`
- `force`
- `use_schema`

**Comment by Remi-Gau** [comment]
Suggested order of parameters:

`BIDS`, `query`, `filter`, `out_path`, `pipeline_name`

**Comment by nbeliy** [comment]
> Should probably ALWAYS be `parameter: value` pairs.


Using inputParser terminology, I will suggest to put all functions that are supposed to be commonly used  by human user to use required and parameters only, with an option of replacing parameters by a structure.

And use required and optional for internal functions.

 Parameters are great to set up default values and let user to hand-pick the options he wants to change, 
but requires to pass by inputParser (or equivalent) to do process, also it relies on constant strings as names of parameters, so a little bit less reliable.

Positional parameters are easy to use, but requires that all parameters before one used must be defined,
which can be bothersome.

So when the straightforwardness is important (user interaction) parameters looks better, and when
doing additional useless checks and robustness is more important use optional, or even only required

**Comment by Remi-Gau** [comment]
Nice ! I think you are describing what I felt was "stricter" option and was not sure about.

> Using inputParser terminology, I will suggest to put all functions that are supposed to be commonly used by human user to use required and parameters only, with an option of replacing parameters by a structure.

Makes sense

> And use required and optional for internal functions.

Yeah I don't think we use parameters for internal function, but I agree with this. 

> Parameters are great to set up default values and let user to hand-pick the options he wants to change, but requires to pass by inputParser (or equivalent) to do process, also it relies on constant strings as names of parameters, so a little bit less reliable.
> 
> Positional parameters are easy to use, but requires that all parameters before one used must be defined, which can be bothersome.

Yup I hear you on this.

> So when the straightforwardness is important (user interaction) parameters looks better, and when doing additional useless checks and robustness is more important use optional, or even only required

OK once we are done with the `File` I will open a PR to deal with this.
