### ISSUE TITLE
Test on octave: dealing with classes ('+' subfolders)

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#3]
I am trying to get some stuff running on a pure octave + SPM12 environment so while I wanted to test this matlab-bids there to see if it behaved well with octave.

Tested on the empty dataset ds001 from the BIDS-example repo.

Running the following that relies on the SPM machinery (i.e `spm_BIDS.m`) works fine
```
docker run -it --rm \
-v /c/Users/Remi/Documents/BIDS/ds001/:/data: \
-v /c/Users/Remi/Documents/BIDS/code/:/code \
spmcentral/spm:octave-latest eval "spm_BIDS('/data/')"
```

But trying to do the same without using SPM by running this fails.
```
docker run -it --rm \
-v /c/Users/Remi/Documents/BIDS/ds001/:/data: \
-v /c/Users/Remi/Documents/BIDS/code/:/code \
spmcentral/spm:octave-latest script '/code/test_bids_matlab.m'
```

With `bids-matlab` in the `/code` folder  and with `test_bids_matlab.m` being:
```
addpath(genpath(fullfile('/code', 'bids-matlab')))
data_dir = '/data/';
BIDS_dir = fullfile(data_dir);
layout  = bids.layout(data_dir)
```

This is the error message I get.

```
Execution failed: /code/test_bids_matlab.m
'file_utils' undefined near line 24 column 16
Error in layout (line 24)
Error in test_bids_matlab (line 4)
Error in spm (line 1218)
Error in run (line 71)
Error in spm (line 1218)
Error in spm_standalone (line 115)
Error in /usr/local/bin/spm12 (line 38)
```

Looks like older version of octave did not deal well with subfolders to define classes (that's what "+" folders are, correct?).
http://octave.1599824.n4.nabble.com/Are-package-folder-supported-td4630147.html

Is that still the case with octave 4.4 (the one that this container uses)?

Am I missing some matlab / octave subtle difference here?

**Comment by gllmflndn** [comment]
Hello,
This is a bug in Octave about private directories in +package:
https://savannah.gnu.org/bugs/?54658
https://savannah.gnu.org/bugs/?45444
I still went ahead and used that feature because I hope it will be fixed at some point and in the meantime one can add explicitly the `+bids` directory in the path - you will get a warning that `addpath: package directories should not be added to path` but the code will run.
This makes me notice a compatibility issue in file_utils.m; I push a short fix shortly.

**Comment by gllmflndn** [comment]
Given that this is a known upstream bug in Octave, I am going to close the issue here. In the meantime, the workaround is to add `+bids` in the path:
```
addpath('bids-matlab', 'bids-matlab/+bids');
```

**Comment by Remi-Gau** [comment]
Noted
