### ISSUE TITLE
Default branch is outdated

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#328]
The default branch (master) is outdated, will it be better to merge dev into master or make dev a default one?

**Comment by Remi-Gau** [comment]
that's normal as the repo follows a gitflow for the realease.

https://github.com/bids-standard/bids-matlab/blob/master/DECISION-MAKING.md#stable-vs-latest-versions-releases-and-fixes

So bug fixes are incorporated into master directly but new features stay in dev until there is a new realease.

**Comment by nbeliy** [comment]
Sorry, missed the updates on master. Closing the issue.
