### ISSUE TITLE
Empty report for ieeg_filtered_speech example

### ISSUE THREAD

**Issue by apjanke** [bids-standard/bids-matlab#35]
When I load and do a `report` on example `ieeg_filtered_speech`, I get an empty report. Is this expected?

```
>> b = bids.layout('bids-examples/ieeg_filtered_speech');
>> bids.report(b)
>> 
```

Same for example `ieeg_motorMiller2007`.

```
>> b = bids.layout('bids-examples/ieeg_motorMiller2007');
>> bids.report(b)
>> 
```

**Comment by Remi-Gau** [comment]
Yup. Report does not cover EEG yet.

The report functionality was done to mimic that of pybids, I am just trying to stick to what they have. But for another project I have in mind to start writing a boiler plate section for MEEG that we could reuse to extend this.

**Comment by apjanke** [comment]
Okay. Closing this out as "by design".
