### ISSUE TITLE
code style suggestion

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#43]
I am tempted to have some suggestions on code style in the repo.

A very easy way to do this would be to use the [miss_hit package](https://github.com/florianschanda/miss_hit.) that can format code automatically to a certain extend and flag things that it cannot fix (like using a certain type of case for the functions, classes). Pretty much like a black or pep8 for matlab.

It can also help enforcing a certain level of code quality (flags functions that are too complex, with too many nested blocks...)

I am using it on several repos and added as part of the CI to ensure consistency.

It is quite tweakable so we could decide on what features to implement.

how do people feel about this? 

@gllmflndn @robertoostenveld @apjanke @tanguyduval

**Comment by Remi-Gau** [comment]
Note: 
- if we decided to enforce a consistent way to name functions (I guess `snake_case` would win) we might have to rename some functions (example: [jsonencode](https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/jsondecode.m)) and thus possibly have some backward compatibility issues (well we don't have a release but I suspect we could create one before doing that).

**Comment by gllmflndn** [comment]
I didn't know about [miss_hit](https://github.com/florianschanda/miss_hit), looks great! Displaying a report for each commit would probably be useful - could you share a link to an example from one of your repos where you use it?

(not sure I would rename `jsonencode` given it's the MATLAB function name and it is also [now available in Octave](https://savannah.gnu.org/bugs/?53100) :tada:).

**Comment by Remi-Gau** [comment]
We have started using it on a couple of repos in my lab:
- https://github.com/cpp-lln-lab/CPP_BIDS
- https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline

What do you mean by a report for each commit? I am not sure I follow.

You mean by using some git hook or using [pre-commit](https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline) to run the linter  on every commit?

**Comment by Remi-Gau** [comment]
> (not sure I would rename `jsonencode` given it's the MATLAB function name and it is also [now available in Octave](https://savannah.gnu.org/bugs/?53100) tada).

Woohoo !!!

**Comment by Remi-Gau** [comment]
Will start a PR to work on this as this should not affect functionality.
