### ISSUE TITLE
[BUG] Querring with explicetly empty sub entity crashes

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

```Markdown
- Linux Ubuntu 18.04 "bionic beaver"
```

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```Markdown
- MATLAB 2017b
```

### bids-matlab version

v0.1.0

### branch / commit number

```Markdown
- main 913246915448505b
```

### Expected Behavior

Usually queries with explicit empty entity for ex. `'acq', []` matches all files:
```matlab
bids.query(BIDS,'subjects', 'ent', [])
ans =
  1x4 cell array
    {'AD0041'}    {'AD0272'}    {'HC0393'}    {'HC1002'}
```
Same behavior is expected for the `sub` entity:
```matlab
bids.query(BIDS,'subjects', 'sub', [])
ans =
  1x4 cell array
    {'AD0041'}    {'AD0272'}    {'HC0393'}    {'HC1002'}
```

### Current Behavior

However in current implementation, passing empty parameter `[]`to `sub` crashes in bids.query>prepare_regex (line 557):
```matlab
bids.query(BIDS,'subjects', 'sub', [])
Index exceeds matrix dimensions.
```

### Error message

```Markdown
Error in bids.query>prepare_regex (line 557)
  if ~strcmp(option(1), '^')

Error in bids.query>check_label_with_regex (line 544)
    option = prepare_regex(option);

Error in bids.query>perform_query (line 355)
    if check_label_with_regex(this_subject.name(5:end), subjects)

Error in bids.query (line 178)
  result = perform_query(BIDS, query, options, subjects, modalities, target, bids_entities);
```

### Anything else?

Incerting at line 554 of `+bids/query.m` (function prepare_regex(option))
```matlab
  if ~ischar(option)
    option = '.*';
    return
  end
```
apparently fix the issue.

**Comment by Remi-Gau** [comment]
Thanks for the detailed report. 

Will also check if that is a problem on the dev branch and push a fix.

**Comment by Remi-Gau** [comment]
Pushing a fix in #455 

Using a different approach to your suggestion because this would actually depart from how the rest of the API works for queries.

Empty strings or empty array are actually used to "exclude" an entity from a query.

So:

```matlab
bids.query(BIDS,'subjects', 'ent', [])
bids.query(BIDS,'subjects', 'ent', '')
```

means exclude subjects that have files that contain the 'ent' entity.

If you want to have subjects that contain the entity ent no matter the value for ent you use `.*`.

```matlab
bids.query(BIDS,'subjects', 'ent', '.*')
```

So in fact your query for subjects should return empty because your query asks to exclude any subjects.

But it should not throw an error, so I made query return early in this case and throw a warning.

Also I was not sure if `''` and `[]` would return the same thing, so I checked for that.

## added test

```matlab
  pth_bids_example = get_test_data_dir();

  BIDS = bids.layout(fullfile(pth_bids_example, 'ds000248'));

  assertEqual(bids.query(BIDS, 'modalities'), {'anat', 'meg'});
  assertEqual(bids.query(BIDS, 'modalities', 'task', '.*'), {'meg'});  % we include any modality with the task entity
  assertEqual(bids.query(BIDS, 'modalities', 'task', 'notPresent'), {}); % no modality with a task called notPresent
  assertEqual(bids.query(BIDS, 'modalities', 'task', ''), {'anat'}); % we exclude the task entity
  assertEqual(bids.query(BIDS, 'modalities', 'task', []), {'anat'});  % we exclude the task entity

  assertEqual(bids.query(BIDS, 'modalities'), {'anat', 'meg'});
  assertEqual(bids.query(BIDS, 'modalities', 'sub', '.*'), {'anat', 'meg'});
  assertEqual(bids.query(BIDS, 'modalities', 'sub', 'notPresent'), {}); 
  assertEqual(bids.query(BIDS, 'modalities', 'sub', ''), {}); % we exclude all subjects
  assertEqual(bids.query(BIDS, 'modalities', 'sub', []), {}); % we exclude all subjects
```

**Comment by nbeliy** [comment]
Tried, it seems to work for me.

Thanks for the quick fix (and for added support of regex for entities) )

**Comment by Remi-Gau** [comment]
thanks for the bug report ! :-)
