### ISSUE TITLE
support for "BIDS model"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#46]
I have started using BIDS model from the [BIDS model BEP](https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit) in the [pipeline of our lab](https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/tree/dev) because not everyone can use [fitlins](https://fitlins.readthedocs.io/en/latest/). :-p

Things are getting to a point where I am thinking to create a function / set of function / class to deal with those (a bit like the analysis module does in pybids).

I think those functionalities would fit better in the bids-matlab repo so I am tempted to work on that here.

My questions are : 

- how do people feel about working on things that are not "vanilla / official" BIDS yet like the BIDS model?
  - pros: 
     - those BEP offer some standard which is better than no standard
     - this BEP might not change much
     - if pybids does it, so can we (I like the idea of both packages being more in synch)
  - con : 
    - we might have to redo some things and potentially break things downstream if people start using bids-matlab once the BEP become official (I think we need to start having versioned releases).
 
- if we agree to support this, how should it be implemented?
  - suggestion : mimicking the pybids implementation maybe? (that I have not looked at yet)

**Comment by apjanke** [comment]
> those BEP offer some standard which is better than no standard

And the way to end up with a good standard is to have working "reference implementations" for practitioners to play with while the standard is still being developed, so they can give feedback based on actual use. I think having "preview" BEP functionality available in the library (or maybe in an add-on "bids-matlab-bep" library) would probably be good for the community and the standard.

**Comment by Remi-Gau** [comment]
Potentially let BIDS matlab help with creating the basic JSON for some simple models.

https://bids-standard.github.io/pybids/analysis/index.html#quickstart
