### ISSUE TITLE
[ENH]: Raise error during derevative generation if no data found

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

In actual state, when using `bids.copy_to_derivative` with incorrect query an warning is raised:

```matlab
>> query.modality = 'xxx';
>> bids.copy_to_derivative(BIDS, 'pipeline_name', 'empty_copy', 'out_path', '..', 'filter', query)
Warning: No data found for this query 
```

Will it be a good idea to replace warning by an error?
Warnings are easily missed by users (especially in pipelines where warnings are surrounded by a lot output), and empty generated derivative dataset can cause non obvious errors downstream.

While the error will force the stop of execution immediately, and it will make much easier to found the cause (incorrect query or incorrect original dataset).

In case if user accepts the possibility of queries without results, it is easy enough to place the `bids.copy_to_derivative` inside a try-catch.

**Comment by Remi-Gau** [comment]
how about we use add a "tolerant" flag for the API of this function like we have in a few others and set it to false by default, so that it will error by default but can be just turned into a warning by switching it to true?

**Comment by Remi-Gau** [comment]
should be fixed.

will try on our labs pipeline.
