### ISSUE TITLE
adding some "write" functions to bids-matlab

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#47]
We created some functions to help write and create several common BIDS files (tsv, json) in this repo.

As most of bids-matlab is for querying already existing BIDS datasets rather than "creating" then I did not thing of suggesting to add those functions in here.

But maybe some of them could have their place here.

https://github.com/cpp-lln-lab/CPP_BIDS
https://github.com/cpp-lln-lab/CPP_BIDS/blob/master/notebooks/basic_usage.ipynb

**Comment by ChristophePhillips** [comment]
I have some bits of code that create BIDS datasets from "collections of .nii volumes". These can be useful when the data have been manually organized by researchers and you want to bring them into BIDS. Typical example are
- for a series of fMRI volumes that need to be aggregated in a 4D volume, renamed as necessary then gzipped;
- for anatomical images, you only need renaming and gzipping,

with appropriate JSON files created/updated along.

The renaming relies on the usual entities for filename (subject label, session, etc.) which are provided by the user, same goes for JSON if the info is not there yet...

**Comment by Remi-Gau** [comment]
BIDS valid filename creation, should now be made easier by the BIDS schema (hopefully). :crossed_fingers:

**Comment by Remi-Gau** [comment]
Closing this since `bids.File` should handle at least the filename creation part
