### ISSUE TITLE
[INFRA] "Workflow"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#48]
I have taken the liberty to "protect" the master branch so that things MUST go through a pull request (though admin can override this). 

I am tempted to create a `dev` branch and to have all PRs that are not bug fixes send there: since we do not have official realeases this could be way to have our "stable" and "latest" release.

Just a thought.

**Comment by sappelhoff** [comment]
or alternatively, treat `master` as "latest", and adopt a versioning scheme and starting to release. Users who want to use the "stable" version could then download and install the GitHub release "assets"

I mean the `.zip` file here (screenshot):

![image](https://user-images.githubusercontent.com/9084751/97140858-d2257680-175d-11eb-9e56-a0f388a3c9ea.png)

Example taken from: https://github.com/bids-standard/bids-validator/releases

**Comment by robertoostenveld** [comment]
I prefer using master for development and having a separate branch for release candidates and tags for releases. Most people new to git and github will develop on their master or will branch off from their master.

**Comment by Remi-Gau** [comment]
Actually I would tempted to say that master should be the stable one because: to cover the usecase where users just download and not clone the repo (which I think is what a lot of matlab users who don't hangout on github will do)

The problem is that we then lose the history and that even if we have `version.txt` in the repo, it might not actually be up to date compared to the version the user is using.

Also I do feel pretty strongly about nudging people to NOT develop on their master branch.

**Comment by robertoostenveld** [comment]
those are good arguments. 

Regarding distribution to matlab users, we should probably plan making it available on https://www.mathworks.com/matlabcentral/fileexchange/

**Comment by apjanke** [comment]
If you want to post it to MathWorks File Exchange, that's probably another argument in favor of making `master` the stable branch and doing dev work on other branches: the Download button on GitHub-linked File Exchange pages will only download the head of master; there's no way to link to GitHub Releases.

**Comment by sappelhoff** [comment]
> Also I do feel pretty strongly about nudging people to NOT develop on their master branch.

agreed

> master should be the stable one because: to cover the usecase where users just download and not clone the repo

yeah ... I'd probably add to your usecase  "and not read the README which tells them how to actually install"

---

so agreed that `master` for the "stable release branch" may be a good idea. It's also how it's done over at another library I use (https://github.com/raphaelvallat/pingouin/)

re matlab file exchange, I agree that that'd be cool to have and in parallel perhaps the octave pkg support (see https://github.com/bids-standard/bids-matlab/issues/26)

**Comment by Remi-Gau** [comment]
> > master should be the stable one because: to cover the usecase where users just download and not clone the repo
> 
> yeah ... I'd probably add to your usecase "and not read the README which tells them how to actually install"

I can't throw stones on that one: I tend to skip that step sometimes. :see_no_evil:

**Comment by Remi-Gau** [comment]
To be more clear on what I had in mind for the "workflow" : it is very close to this. 

![ ](https://blog.axosoft.com/wp-content/uploads/2017/01/gitflow-diagram-768x973.png)

From here.
https://blog.axosoft.com/gitflow/
