### ISSUE TITLE
use the standard column name trial

### ISSUE THREAD

**Issue by CPernet** [bids-standard/bids-matlab#505]
change face_type in https://github.com/bids-standard/bids-matlab/blob/61e8ac22454326206ce6c132218f5c70074a4c6d/demos/spm/facerep/code/convert_facerep_ds.m#L128 to trial_type as defined in https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.columns.trial_type

**Comment by Remi-Gau** [comment]
fixed by #507
