### ISSUE TITLE
Files with no ses entity in a ses folder not indexed when relying on schema

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#591]
sub-01/ses-01/anat/sub-01_t1w.nii

Should be indexed when not relying on schema but it does not seem to be.

**Comment by nbeliy** [comment]
I would say that they shouldn't be indexed -- BIDS impose `sub-123_ses-456` for files with session. This is not related to a schema of a given modality.

**Comment by Remi-Gau** [comment]
> BIDS impose sub-123_ses-456 for files with session. 

yes but the way bids-layout behaves when not relying on the schema is to ignore these rules and just parse index files as long as their filenames follow the pattern
```
entity-label[_entity-label]*_suffix.extension
```
without query about the nature or the order of the entities.
