### ISSUE TITLE
[BUG] Crash during processing empty subject folder

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

```Markdown
- Linux Ubuntu 20.04.6 LTS "focal"
```

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```Markdown
- MATLAB 2017b
```

### bids-matlab version

v0.1.0

### branch / commit number

```Markdown
- master 4662928
```

### Expected Behavior

When running on `bids.layout` on dataset with empty subject folder (no data types folders), I would expect it will ignore empty subjects, preferably with a warning:
```matlab
Warning: subject '/home/beliy/tests/test_ds/sub-001' contains an invalid subfolder ''. Skipping.
```

### Current Behavior

When running on `bids.layout` on dataset with empty subject folder (no data types folders), it crashes with `Index exceeds matrix dimensions.` error.

### Error message

```Markdown
Index exceeds matrix dimensions.

Error in bids.internal.is_valid_fieldname (line 33)
  invalid_first_characters = regexp(some_str(1), '[^a-zA-Z]', 'match');

Error in bids.layout>parse_subject (line 264)
          if ~bids.internal.is_valid_fieldname(modalities{iModality})

Error in bids.layout (line 131)
        BIDS.subjects = parse_subject(BIDS.pth, subjects{iSub}, sessions{iSess}, ...
```

### Anything else?

An easy fix is to adapt lines 22 in `+bids/+internal/is_valid_fieldname.m`, similar to:
```matlab
  if length(some_str) > namelengthmax ||  length(some_str) < 0
    status = false;
    return
  end
```

I think the better way is to fix `return_modalities` function from `+bids/Schema.m:90`, so it will return an empty cell if folder is empty.

Also, would it be easier to collect the two regexp in `is_valid_fieldname` to one regexp, something like:
```matlab
res = regexp(some_str, '^[a-zA-Z][a-zA-Z0-9_]*$', 'match');
if isempty(res)
  status = false;
  return;
end
```
I think it will simplify the code

**Comment by Remi-Gau** [comment]
Thanks for the report.
Out of curiosity: do you know if the bug exists on the dev branch?

**Comment by nbeliy** [comment]
Checked in dev:
 - no error
 - No warnings (both with verbose and without)
 - layout is created with an empty subject:
```matlab
ds.subjects

ans = 

  struct with fields:

       name: 'sub-001'
       path: '/home/beliy/tests/test_ds/sub-001'
    session: ''
       sess: ''
      scans: ''
```

I think a warning is necessary, and no empty subjects in the final layout (may mess with loops).

**Comment by Remi-Gau** [comment]
thanks for checking
agreed on the warning and indeed if the subject has no file at all it is kind of strange to add it into the layout
