### ISSUE TITLE
[BUG] Unexpexted warning during error report with missing `participants.json` on Windows

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [X] Windows

### Operating system version

```Markdown
- Windows11
```

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```Markdown
- Matlab2022 (?)
```

### bids-matlab version

v0.1.0dev

### branch / commit number

```Markdown
dev
main
```

### Current Behavior

If there no `participants.json` in the dataset, the `bids.layout` will generate an error message using `+bids/+internal/error_handling.m`. In particular, on line 51:
```matlab
msg = sprintf(['\n' args.Results.msg '\n']);
```
where `args.Results.msg` comtains path to the missing file.

However on windows paths contains `\`, which can create (non-existing) special characters and make `sprintf` unhappy:
```matlab
>> sprintf('D:\Home\Users\abc\def')
Warning: Escaped character '\H' is not valid. See 'doc sprintf' for supported special characters. 

ans =

    'D:'
```

Replacing `sprintf` by `strcat` seems to fix the issue:
```matlab
>> strcat('\n', 'D:\Home\Users\abc\def', '\n')

ans =

    '\nD:\Home\Users\abc\def\n'
```

P.S. Happened not on my computer, and wasn't managed to save the error trace(

### Anything else?

Is it possible to invert in the bug report template `Expected` and `Current` blocks?

**Comment by Remi-Gau** [comment]
I think this relates to 
- https://github.com/bids-standard/bids-matlab/issues/564

There are a few of those left I have not got around to tackle.

**Comment by nbeliy** [comment]
If you want, I can try to track them, if the solution above (replacing sprintf by strcat, or []) is acceptable.

**Comment by gllmflndn** [comment]
What about using this syntax instead?
```
sprintf('\n%s\n', args.Results.msg);
```

**Comment by nbeliy** [comment]
Depends if it works in Windows, (in linux it does).

Just for personal information, why use sprintf instead of []? More efficient/secure?

**Comment by gllmflndn** [comment]
`strcat` or `[]` will not handle special characters like `\n` and you would have to use `newline` instead. Apart from that, it's a matter of taste I presume.

I haven't looked at the code but if the variable `msg` is later used directly in `fprintf`/`error`/`warning` then the backslashes `\` should be escaped to `\\` otherwise you would still get a warning down the line. Using `%s` throughout makes this issue disappear.

**Comment by Remi-Gau** [comment]
Will take some time to fix this because some of the output on windows is starting  light up like a Xmas tree with so many warnings

**Comment by Remi-Gau** [comment]
Things look a bit better better by relying on `bids.internal.format_path` but not yet perfect as I still get a few issues from some logs in CI.
Closing for now but reopen if things are not solved for you when using the dec branch.
