### ISSUE TITLE
multi-file datasets should not be represented differently than single files 

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-matlab#6]
If I have a data collection with BDF data (one file per recording), and if I would convert the BDFs to BrainVision (triplets), I would expect the same BIDS layout to be returned and the same MATLAB analysis script to run. The script should not have to care about file formats, but simply pass them into e.g. ft_preprocessing.

**Comment by gllmflndn** [comment]
Fixed in https://github.com/bids-standard/bids-matlab/pull/14. Closing.
