### ISSUE TITLE
tsvwrite writes non-compliant tsvs when a table is provided

### ISSUE THREAD

**Issue by coxroy** [bids-standard/bids-matlab#603]
whenever a Matlab table is provided to `tsvwrite`, Matlab's builtin `writetable` is used to write the tsv. this can result in noncompliant tsvs if the user did not manually think to change empty/NaN/NaT/etc values to n/a.

possible solution is to call `table2struct` whenever a table is provided, with this struct then undergoing the already present checks for noncompliant values

**Comment by Remi-Gau** [comment]
Can reproduce the bug in dev and in master.
will push a hot fix in master.
