### ISSUE TITLE
Some files cannot be queried when placed in the subject / session folder

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#64]
If stimulus presentation was the same for all participants, event.tsv files can be set in the root folder (inheritance principle).

But it seems that `bids.query` fails to find it.

Here is a minimal working example of the bug using the bids-example repo.

This also affects `spm_BIDS`

```
BIDS = bids.layout(fullfile(pwd,  'ds114'));

% query for any event file for one task comes back empty
event_file = bids.query(BIDS, 'data', ...
                        'task', 'overtverbgeneration', ...
                        'type', 'events')

event_file =

  0×0 empty cell array

% yet the file is present in the root of this dataset
dir(fullfile(pwd,  'ds114',  'task-overtverbgeneration_events.tsv'))

task-overtverbgeneration_events.tsv  
```

**Comment by gllmflndn** [comment]
Confirmed. There is a [comment about this in the code](https://github.com/bids-standard/bids-matlab/blob/9f46a671f9ae79c8c3b2da58201f122d46d07ece/%2Bbids/layout.m#L246).
