### ISSUE TITLE
[ENH]:  `file.rename` could change `.` to `pt` in the case of `spec.entities.xxx = num2str(1.5)`

### ISSUE THREAD

**Issue by marcobarilari** [bids-standard/bids-matlab#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Hi there, 

thanks for this useful tool.

I was wondering if there is any option to get `file.rename` deal with eg `spec.entities.xxx = num2str(1.5)` so that in the renamed file name the output is eg `..._xxx-1pt5_...` and not `..._xxx-15_...`

**Comment by Remi-Gau** [comment]
yeah I think this is something we could implement
