### ISSUE TITLE
Move tests from Travis to GitHub Actions to test on all OSses

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-matlab#68]
GitHub Actions allows for easy testing on Windows, MacOS, and Linux, which would improve the testing pipeline to also cover "special" bugs that only appear on some OSses.

**Comment by Remi-Gau** [comment]
Hum... Even with matlab and octave?

I know that Travis actually now supports Matlab in their CI so we could have both there. Not sure about github actions.

**Comment by sappelhoff** [comment]
> Hum... Even with matlab and octave?

Octave yes (not sure about Windows to be honest) - but Matlab probably not. I didnt know that Travis supports Matlab in their CI, that's awesome ... and a bit puzzling to me how they deal with the licensing issues :)

**Comment by Remi-Gau** [comment]
Well I don't know much more than that: https://twitter.com/RemiGau/status/1310681042714537991
And I have not tested it yet

**Comment by sappelhoff** [comment]
I now found this: https://github.com/joergbrech/moxunit-action

but haven't tested it yet.

> This action performs unit tests for GNU Octave and **Matlab** using the unit testing framework MOxUnit. 

Looks like we need some time and energy to test a couple of alternatives :-)

**Comment by Remi-Gau** [comment]
Ha yeah we started thinking about using MOxUnit in #44 .

No decision has been made about this yet. But it definitely is an option that can also get you your code coverage in one fell swoop.

**Comment by gllmflndn** [comment]
In general, I would also prefer to use GitHub Actions to anything else but if we want to test with MATLAB and not just Octave, we might have to (temporarily) still use another platform. This [page](https://www.mathworks.com/solutions/continuous-integration.html) only mentions CircleCI and Travis, while [this one](https://www.mathworks.com/help/matlab/matlab_prog/continuous-integration-with-matlab-on-ci-platforms.html) does not mention [Travis](https://docs.travis-ci.com/user/languages/matlab/).

**Comment by Remi-Gau** [comment]
@sappelhoff 

any pointer on trying to adapt our github action workflows to run our tests also on MacOS and Windows (for octave)?

I don't have the bandwidth to look on setting up CI tests with matlab at the moment.

**Comment by sappelhoff** [comment]
Yes, I think setting up for at least MacOS will be relatively straight forward: You will just have to make another step like this one:

https://github.com/bids-standard/bids-matlab/blob/6c1dac65880df28b69ec131983cd8bbbfce1c258/.github/workflows/run_tests.yml#L22-L26

but ensure that the (then two) steps run depending on the OS. that is, one runs only when OS=ubuntu, the other one only when OS=macOs

For the Ubuntu step, you leave everything as it is ... and for the MacOS step you adjust the "apt" installs with "brew" installs. The remaining action *should* work regardless of ubuntu or MacOS.

--> for **windows** it would go the same way ... first duplicating the steps, then making them run conditionally on a single OS only, and then adjusting the duplicated-OS-specific steps to actually work on that OS. I mean -> apt on ubuntu, brew on macOS, and maybe [chocolatey](https://chocolatey.org/) on windows, ... and so on for all other commands.

I am not sure how easy this will be with windows. I once managed it for a similarly "complicated" install for the bids-validator. Hopefully it can serve as an example of what I mean:

https://github.com/sappelhoff/bids-validator/blob/407b94c388bf36005069e0a4f0c67a21fbcdc8b8/.github/workflows/python_tests.yml#L14-L42

**Comment by Remi-Gau** [comment]
Awesome. Thanks for all those pointers.

Moving this to a separate issue. :wink:

**Comment by acampbel** [comment]
HI all,

This seems relevant:

https://github.com/matlab-actions

They are not in the marketplace yet, but they work just as the travis, circle, and azure DevOps extensions.

Have fun!
Andy
