### ISSUE TITLE
[BUG] bids.init adds a participant id with a duplicated sub entity prefix

### ISSUE THREAD

**Issue by achilleasNP** [bids-standard/bids-matlab#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

```Markdown
- Linux Debian
```

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```Markdown
- Matlab R2023b
```

### bids-matlab version

v0.1.0dev

### branch / commit number

```Markdown
- main 6e2a3fb3513127
```

### Expected Behavior

Participants files should have contained:
```
participant_id
sub-a
```

### Current Behavior

Participant file contains:
```
participant_id
sub-sub-a
```

### Anything else?

Matlab code for reproducing the error
```matlab
bids.init('t2', folders = struct('subjects', 'a', 'sessions', '1', 'modalities', 'beh'))
```

**Comment by Remi-Gau** [comment]
Can reproduce.
Will push a fix shortly.

**Comment by Remi-Gau** [comment]
This bug and #686 should now be fixed.
