### ISSUE TITLE
[BUG] bids.init generated sessions file missing ses label from session_id column

### ISSUE THREAD

**Issue by achilleasNP** [bids-standard/bids-matlab#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

```Markdown
- Linux Debian testing
```

### Platform

- [ ] MATLAB
- [X] Octave

### Platform version

```Markdown
Matlab R2023b
```

### bids-matlab version

v0.1.0dev

### branch / commit number

```Markdown
- main 6e2a3fb35131275351ca59199d114bc9979aab4c
```

### Expected Behavior

Content of sub-a/sub-a_sessions.tsv 
```
session_id	acq_time	comments
ses-1	n/a	n/a
```

### Current Behavior

Content of sub-a/sub-a_sessions.tsv 
```
session_id	acq_time	comments
ses-	n/a	n/a
```

### Anything else?

Code to generate error
```matlab
bids.init('t1', folders = struct('subjects', 'a', 'sessions', '1', 'modalities', 'beh'))
```

**Comment by Remi-Gau** [comment]
Thanks for the report.
Will try to reproduce when I am in front of a computer.

**Comment by Remi-Gau** [comment]
Can reproduce.
Will push a fix shortly.

**Comment by Remi-Gau** [comment]
@all-contributors please add @achilleasNP for bug
