### ISSUE TITLE
Vendor a JSONio fork?

### ISSUE THREAD

**Issue by apjanke** [bids-standard/bids-matlab#92]
Installing Matlab libraries for use with other libraries is a big pain. There's no standard mechanism to do so, so it's "some assembly required" for end users. So having dependencies sucks. BIDS-MATLAB users on Matlab pre-R2016b need to figure out how to install JSONio or SPM12 in one of their environments.

What do you think about bundling a version of JSONio or SPM12 with BIDS-MATLAB itself, and have BIDS-MATLAB automatically pull it in if it detects that it is needed? That way BIDS-MATLAB users wouldn't have to worry about it, and you could guarantee that the version of the JSON library that BIDS-MATLAB is using is one that it is tested against.

You could make a minor fork of one of them and stick it under a `+bids/+internal/+opp` package to prevent it from conflicting with any user-installed JSONio or SPM12. ("opp" standing for "other parties' programs" here.)

Wouldn't work for Octave (without getting really fancy), because oct-files need to be built for the specific Octave installation they're running against. (Or maybe Octave can use MEX files now? I can't remember the binary-compatibility situation.)

**Comment by CPernet** [comment]
Hi Andrew, just pining here the relevant people @Remi-Gau @gllmflndn 
I had the same issue today looking at a converter  @mnoergaard  wrote and spm12 wasn't installed - the json output looks crap --> Guillaume can we fork https://github.com/gllmflndn/JSONio in this repo (then call json_write with prettyprint rather than if do matlab else do spm)

**Comment by gllmflndn** [comment]
> and spm12 wasn't installed

:open_mouth:

**Comment by CPernet** [comment]
sorry .. wasn't in the matlab path

**Comment by gllmflndn** [comment]
:relieved:
Latest [Matlab](https://www.mathworks.com/help/matlab/ref/jsonencode.html#mw_69b38ba2-26d1-4025-a426-d1bf8ca939a7) and [Octave](https://savannah.gnu.org/bugs/index.php?60259) now have a `PrettyPrint` option and JSONio is just a temporary option until everyone has access to these latest releases. That said, [jsonwrite](https://github.com/gllmflndn/JSONio/blob/main/jsonwrite.m) is written as a pure M-file so copying it over shouldn't be a problem.
