### ISSUE TITLE
Fail to capture all EEG files and wrong number of subjects

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-matlab#97]
Only capture the raw data, channel and event file. Misses the JSON files.
Also, there are only 2 subjects (with 3 sessions each). Yet the program think there are 6 subjects

<img width="455" alt="Screen Shot 2020-11-13 at 10 49 21 AM" src="https://user-images.githubusercontent.com/1872705/99119934-1f974580-259e-11eb-9a0b-cc03bd547646.png">
<img width="521" alt="Screen Shot 2020-11-13 at 10 49 12 AM" src="https://user-images.githubusercontent.com/1872705/99119942-21f99f80-259e-11eb-94cf-f36aab20870c.png">

**Comment by Remi-Gau** [comment]
hey @arnodelorme 

Try to use `bids.query` to access specific pieces of information of the layout. This is how the whole thing has been designed. :wink: 

I still need to write some sort of official doc on this but in the mean time you can look at [test_bids_query](https://github.com/bids-standard/bids-matlab/blob/master/tests/test_bids_query.m) as a source of unofficial doc.

In your case, what do the following give you? 

```
bids.query(res, 'subjects')
bids.query(res, 'data', 'sub', '01')
```

Also I am pretty sure that JSON files are not "indexed". Am I right @gllmflndn?

If you want to get the content of some JSON file you would need to do something like this:

```
bids.query(res, 'metadata', 'sub', '01', 'task', 'Experiment')
```

**Comment by arnodelorme** [comment]
Why not load it all?

**Comment by Remi-Gau** [comment]
Not sure why that initial decision was made though I suspect that this in part related to dealing with the inheritance principle which implies that the metadata about a given file could be spread in several JSON, so this is dealt with on the fly when metadata is requested.

**Comment by Remi-Gau** [comment]
hey @arnodelorme

PR #47 should be able to index the json files that are in any "modality" folder a subject if you ask for a schema-less layout.

```matlab
use_schema = true();
BIDS = bids.layout(fullfile(pth_bids_example, 'eeg_rishikesh'), use_schema);
bids.query(BIDS, 'data', 'sub', '001', 'ses', '01')

ans =

  3×1 cell array

    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_channels.tsv'
    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_eeg.bdf'
    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_events.tsv'

%%
use_schema = false();
BIDS = bids.layout(fullfile(pth_bids_example, 'eeg_rishikesh'), use_schema);
bids.query(BIDS, 'data', 'sub', '001', 'ses', '01')

ans =

  4×1 cell array

    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_channels.tsv'
    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_eeg.bdf'
    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_eeg.json'
    'bids-examples/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_events.tsv'

```
I have shortened the full path in the copy-paste to make it easier to read.

Will merge the PR in the `dev` branch

**Comment by arnodelorme** [comment]
Thank you
